config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  resources :runs do
    collection do
      get 'search'
    end
  end
  resources :shoes
  resources :weather_types, except: [:show]
  get 'training' => 'static_pages#training'
end

app/controllers/weather_types_controller.rb
class WeatherTypesController < ApplicationController
  def index
    @weather_types = WeatherType.all.paginate(per_page: 20, page: params[:page])
    min_temp, max_temp = Run.pluck(:temperature).compact!.minmax
    @temp_counts = {}
    (min_temp / 5).upto(max_temp / 5).each do |temp_category|
      label = "#{temp_category * 5}&ndash;#{temp_category * 5 + 4}".html_safe
      @temp_counts[label] = Run.where(temperature: temp_category * 5...(temp_category + 1) * 5).count
    end
  end

  def new
    @weather_type = WeatherType.new
  end

  def edit
    @weather_type = WeatherType.find(params[:id])
  end

  def create
    @weather_type = WeatherType.new(weather_type_params)
    if @weather_type.save
      flash[:success] = 'Weather type was successfully created.'
      redirect_to weather_types_path
    else
      flash[:danger] = @weather_type.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    @weather_type = WeatherType.find(params[:id])
    if @weather_type.update(weather_type_params)
      flash[:success] = 'Weather type was successfully updated.'
      redirect_to weather_types_path
    else
      flash[:danger] = @weather_type.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @weather_type = WeatherType.find(params[:id])
    @weather_type.destroy
    flash[:success] = 'Weather type was successfully deleted.'
    redirect_to weather_types_path
  end

  private

  def weather_type_params
    params.require(:weather_type).permit(:name, :is_precip, :day_icon, :night_icon)
  end
end

app/helpers/weather_types_helper.rb
module WeatherTypesHelper
end

app/views/weather_types/_form.html.haml
= form_for(weather_type) do |f|
  .row.mb-3
    = f.label :name, 'Name', class: 'col-sm-3 col-form-label'
    .col-sm-4.col-md-3
      = f.text_field :name, class: 'form-control'
  .row.mb-3
    .col-sm-4.col-md-3.offset-sm-3
      .form-check
        = f.check_box :is_precip, class: 'form-check-input'
        %label.form-check-label
          Precipitation?
  .row.mb-3
    = f.label :day_icon, 'Day icon', class: 'col-sm-3 col-form-label'
    .col-sm-4.col-md-3
      = f.text_field :day_icon, class: 'form-control'
  .row.mb-3
    = f.label :night_icon, 'Night icon', class: 'col-sm-3 col-form-label'
    .col-sm-4.col-md-3
      = f.text_field :night_icon, class: 'form-control'
  .row.mb-3
    .col-sm-7.offset-sm-3
      = submit_tag button_title, class: 'btn btn-primary'
      - unless weather_type.new_record?
        = link_to 'Delete', weather_type, data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'

app/views/weather_types/_weather_type.html.haml
%tr
  %td.text-center
    =link_to weather_type.name, edit_weather_type_path(weather_type)
  %td.text-center=weather_type.is_precip ? 'yes' : 'no'
  %td.text-center=build_icon(weather_type.day_icon)
  %td.text-center=build_icon(weather_type.night_icon)
  %td.text-center=weather_type.runs.size

app/views/weather_types/edit.html.haml
- provide(:title, 'Edit weather type')
.col-12
  %h1 Edit weather type
  = render 'form', button_title: 'Update', weather_type: @weather_type
  = link_to 'Back', weather_types_path, class: 'btn btn-secondary'

app/views/weather_types/index.html.haml
- provide(:title, 'Weather types')
.row
  .col-12
    %h1 Weather statistics
    .card
      .card-header
        Temperatures
      .card-body
        - @temp_counts.each do |temp, count|
          = render 'shared/graph_bar', bar_height: count,
                                      tooltip: pluralize(count, 'run'),
                                      label_category: temp,
                                      label_amount: count
    .text-center
      =will_paginate(@runs, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer)
    .card
      .card-header=page_entries_info
      %table.table.table-hover
        %thead
          %tr
            %th Name
            %th Precipitation?
            %th Day icon
            %th Night icon
            %th Number of runs
        %tbody
          = render @weather_types
          %tr
            %td.text-center (not specified)
            %td
            %td
            %td
            %td.text-center=Run.where(weather_type_id: nil).size
    .text-center
      =will_paginate(@runs, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer)
    = link_to 'New Weather Type', new_weather_type_path, class: 'btn btn-large btn-success'

app/views/weather_types/new.html.haml
- provide(:title, 'New weather type')
.col-12
  %h1 New weather type
  = render 'form', button_title: 'Create', weather_type: @weather_type
  = link_to 'Back', weather_types_path