config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  resources :runs do
    collection do
      get 'search'
    end
  end
  resources :shoes
  resources :weather_types, except: [:show]
  get 'training' => 'static_pages#training'
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :shoe, optional: true
  belongs_to :weather_type, optional: true

  scope :last_week, -> { where start_time: (Time.now - 1.week)..Time.now }
  scope :on_day, ->(day) { where start_time: day.beginning_of_day...day.end_of_day }
  scope :last_days_from, ->(days, time) { where start_time: (time - (days - 1).days).beginning_of_day...time.end_of_day }

  validates :start_time, presence: true
  validates :distance, numericality: { greater_than: 0 }
  validates :duration, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :temperature, numericality: { only_integer: true }, allow_nil: true
  validates :elev_gain, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :humidity, numericality: 0..100, allow_nil: true
  validates :intensity, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

  def similar_runs(limit = 5)
    comparable_runs = Run.all.select(&:can_be_compared?)
    dists = comparable_runs.map(&:distance)
    hills = comparable_runs.map(&:climb_rate)
    temps = comparable_runs.map(&:temperature)
    paces = comparable_runs.map(&:pace)

    dist_range = dists.max - dists.min
    hill_range = hills.max - hills.min
    temp_range = (temps.max - temps.min) * 1.0
    pace_range = paces.max - paces.min

    runs = comparable_runs.reject { |r| r == self }
    runs.map! do |r|
      {
        run: r,
        similarity: similarity(r,
                               dist_range: dist_range,
                               hill_range: hill_range,
                               temp_range: temp_range,
                               pace_range: pace_range)
      }
    end
    runs.sort! { |a, b| b[:similarity] <=> a[:similarity] }
    runs[0...limit]
  end

  def similarity(other, dist_range: 0, hill_range: 0, temp_range: 0, pace_range: 0)
    return 0 unless other.is_a? Run
    return 0 unless can_be_compared? && other.can_be_compared?

    sim_dist = dist_range.zero? ? 1 : 1 - (distance - other.distance).abs / dist_range
    sim_hill = hill_range.zero? ? 1 : 1 - (climb_rate - other.climb_rate).abs / hill_range
    sim_temp = temp_range.zero? ? 1 : 1 - (temperature - other.temperature).abs / temp_range
    sim_pace = pace_range.zero? ? 1 : 1 - (pace - other.pace).abs / pace_range

    (sim_dist + sim_hill + sim_temp + sim_pace) / 4
  end

  def can_be_compared?
    distance? && elev_gain? && temperature?
  end

  def validate
    errors.add(:start_time, 'is invalid') if @invalid_start_time
  end

  def start_time_string=(start_time_str)
    self.start_time = Time.parse(start_time_str)
  rescue ArgumentError
    @invalid_start_time = true
  end

  def start_time_string
    time = id? ? start_time : Time.now
    time.strftime('%Y-%m-%d %H:%M')
  end

  def day_of_week
    start_time.strftime('%A')
  end

  def time_of_day
    case start_time.hour
    when 4..11
      "#{day_of_week} morning"
    when 12..16
      "#{day_of_week} afternoon"
    when 17..21
      "#{day_of_week} evening"
    else
      "#{day_of_week} overnight"
    end
  end

  def duration_string=(str)
    self.duration = str.split(':').inject(0) { |a, m| a * 60 + m.to_i }
  end

  def duration_string
    duration? ? time_string(duration) : ''
  end

  def pace
    duration / distance
  end

  def distance_record?
    prev_distance_record = Run.where('start_time < :time', { time: start_time }).maximum('distance')
    distance? && (!prev_distance_record || distance > prev_distance_record)
  end

  def pace_record?
    duration? && Run.where('start_time < :time', { time: start_time }).select do |r|
      r.distance >= distance && r.duration? && r.pace <= pace
    end.empty?
  end

  def pace_string
    duration? ? "#{time_string(pace)}/mi" : 'N/A'
  end

  def climb_rate
    elev_gain / distance
  end

  def precip?
    weather_type&.is_precip?
  end

  def shoe_name
    [shoe.manufacturer, shoe.model].join(' ')
  end

  def previous
    Run.where(['start_time < ?', start_time]).order(start_time: :desc).first
  end

  def next
    Run.where(['start_time > ?', start_time]).order(:start_time).first
  end

  def shoe_mileage
    shoe&.mileage(as_of: start_time).round(2)
  end

  def dewpoint
    temp_c = (temperature - 32) * 5.0 / 9
    hum_pct = humidity * 0.01
    257.14 * Math.log(hum_pct * Math.exp((18.678 - temp_c / 234.5) * (temp_c / (257.14 + temp_c)))) / (18.678 - Math.log(hum_pct * Math.exp((18.678 - temp_c / 234.5) * (temp_c / (257.14 + temp_c))))) * 9 / 5 + 32
  end

  private

  def time_string(seconds)
    if seconds < 3600
      Time.at(seconds).strftime('%-M:%S')
    else
      h = seconds / 3600
      "#{h}:" + Time.at(seconds).strftime('%M:%S')
    end
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :find_run, only: %i[show edit destroy update]

  def index
    criteria = {}

    if params[:filter_date]
      begin_time = Time.new(*params[:start_date].split('-')).beginning_of_day
      end_time = Time.new(*params[:end_date].split('-')).end_of_day
      criteria[:start_time] = begin_time..end_time
    end

    criteria[:distance] = params[:min_dist]..params[:max_dist] if params[:filter_dist]
    criteria[:temperature] = params[:min_temp]..params[:max_temp] if params[:filter_temp]
    # criteria[:is_race] = true if params[:type] == 'race'

    run_list = if criteria.any?
                 Run.where(criteria).order(start_time: :desc)
               else
                 Run.all.order(start_time: :desc)
               end

    run_list = params[:type] == 'race' ? run_list.select(&:is_race) : run_list

    @runs = run_list.paginate(per_page: 50, page: params[:page])

    respond_to do |format|
      format.html
      format.xml { render xml: run_list }
      format.json { render json: run_list }
    end
  end

  def show
    @shoe = Shoe.find(@run.shoe_id) rescue nil

    respond_to do |format|
      format.html
      format.xml { render xml: @run }
    end
  end

  def new
    @run = Run.new
  end

  def edit; end

  def create
    convert_datetime_to_local('start_time')
    @run = Run.new(run_params)
    if @run.save
      flash[:success] = 'Run was successfully created.'
      redirect_to @run
    else
      flash[:danger] = @run.errors.full_messages
      render :new
    end
  end

  def update
    convert_datetime_to_local('start_time')
    if @run.update(run_params)
      flash[:success] = 'Run was successfully updated.'
      redirect_to @run
    else
      flash[:danger] = @run.errors.full_messages
      render :edit
    end
  end

  def destroy
    @run.destroy
    flash[:success] = 'Run was successfully deleted.'
    redirect_to action: :index
  end

  def search
    date = Time.now
    @start_date = (date - 1.year).strftime('%Y-%m-%d')
    @end_date = date.strftime('%Y-%m-%d')
  end

  private

  def find_run
    @run = Run.find(params[:id])
  end

  def run_params
    params.require(:run).permit(:distance, :elev_gain, :start_time_string,
                                :temperature, :duration_string, :is_race,
                                :notes, :race_name, :shoe_id, :is_night,
                                :weather_type_id, :heart_rate, :humidity,
                                :intensity)
  end

  def convert_datetime_to_local(field)
    datetime = (1..5).collect { |num| params['run'].delete "#{field}(#{num}i)" }
    if datetime[0] && datetime[1] && datetime[2]
      params['run'][field] = Time.find_zone!('Eastern Time (US & Canada)').local(*datetime.map(&:to_i))
    end
  end
end

app/helpers/runs_helper.rb
module RunsHelper

  def temp_class(temp)
    return nil if temp.nil?

    "temp#{temp / 10 * 10}"
  end

  def build_page_title(params)
    page_title_class = params[:type]&.pluralize || 'runs'
    if params[:year]
      "#{page_title_class.capitalize} in #{params[:year]}"
    elsif params[:start_date]
      'Search results'
    else
      "All #{page_title_class}"
    end
  end

  def star_output(rating)
    return '' if rating.nil?

    star = build_icon('star')
    half = build_icon('star-half')
    if rating < 45
      title = 'awful'
      content = half
    elsif rating < 65
      title = 'poor'
      content = star
    elsif rating < 80
      title = 'okay'
      content = star + half
    elsif rating < 90
      title = 'decent'
      content = star * 2
    elsif rating < 100
      title = 'average'
      content = star * 2 + half
    elsif rating < 110
      title = 'solid'
      content = star * 3
    elsif rating < 120
      title = 'good'
      content = star * 3 + half
    elsif rating < 135
      title = 'great'
      content = star * 4
    elsif rating < 155
      title = 'excellent'
      content = star * 4 + half
    else
      title = 'awesome'
      content = star * 5
    end
    "<span title=#{title} data-toggle=tooltip>#{content}</span>".html_safe
  end

  def local_time_string(time)
    time.strftime('%l:%M %p')
  end

  def local_date_time_string(time)
    time.strftime('%a %-m/%-d/%y %-l:%M %p')
  end
end

app/views/runs/_form.html.haml
= render 'intensity_calc'
= form_for(run) do |f|
  .row.mb-3
    = f.label :start_time_string, 'Start time', class: 'col-sm-3 col-form-label'
    .col-sm-5.col-md-4.col-lg-3
      .input-group.date#start-time{'data-target-input': 'nearest'}
        = f.text_field :start_time_string, id: 'start-time', class: 'form-control datetimepicker-input', 'data-target': '#start-time'
        .input-group-text{data: {target: '#start-time', toggle: 'datetimepicker'}}
          %i.fa.fa-calendar
  .row.mb-3
    .col-sm-4.col-md-3.offset-sm-3
      .form-check
        = f.check_box :is_night, class: 'form-check-input'
        %label.form-check-label
          Night run
  .row.mb-3
    = f.label :distance, 'Distance', class: 'col-sm-3 col-form-label'
    .col-sm-4.col-md-3.col-lg-2
      .input-group
        = f.number_field :distance, class: 'form-control', step: 0.01, min: 0
        .input-group-text miles
  .row.mb-3
    = f.label :duration_string, 'Duration', class: 'col-sm-3 col-form-label'
    .col-sm-5.col-md-4.col-lg-3
      = f.text_field :duration_string, class: 'form-control'
      .form-text mm:ss or h:mm:ss format
  .row.mb-3
    = f.label :temperature, 'Weather', class: 'col-sm-3 col-form-label'
    .col-sm-3.col-lg-2
      .input-group
        = f.number_field :temperature, class: 'form-control', in: -10..110
        .input-group-text &deg;F
      .form-text temperature
    .col-sm-3.col-xl-2
      = f.select :weather_type_id, WeatherType.all.collect {|wt| [wt.name, wt.id]}, {include_blank: true}, class: 'form-select'
      .form-text conditions
    .col-sm-3.col-lg-2
      .input-group
        = f.number_field :humidity, class: 'form-control', in: 0..100
        .input-group-text %
      .form-text humidity
  .row.mb-3
    = f.label :elev_gain, 'Elevation gain', class: 'col-sm-3 col-form-label'
    .col-sm-4.col-md-3.col-lg-2
      .input-group
        = f.number_field :elev_gain, class: 'form-control', min: 0
        .input-group-text feet
  .row.mb-3
    = f.label :heart_rate, 'Heart rate', class: 'col-sm-3 col-form-label'
    .col-sm-4.col-md-3.col-lg-2
      .input-group
        = f.number_field :heart_rate, class: 'form-control', min: 0, max: 250
        .input-group-text bpm
  .row.mb-3
    = f.label :intensity, 'Intensity points', class: 'col-sm-3 col-form-label'
    .col-sm-3.col-md-2
      .input-group
        = f.number_field :intensity, class: 'form-control', step: 0.01, min: 0
        .input-group-text{data: {'bs-toggle': 'modal', 'bs-target': '#intensity-calc'}}
          %i.fas.fa-calculator
  .row.mb-3
    .col-sm-5.col-md-4.offset-sm-3
      .form-check
        = f.check_box :is_race, class: 'is-race-checkbox form-check-input'
        %label.form-check-label
          This run is a race
    .col-sm-5.offset-sm-3.offset-md-0
      = f.text_field :race_name, class: 'form-control race-name-input', placeholder: 'Race name', style: 'display: none'
  .row.mb-3
    = f.label :shoe_id, 'Shoe', class: 'col-sm-3 col-form-label'
    .col-sm-4.col-md-3
      = f.select :shoe_id, Shoe.active.collect {|s| [model_with_mileage(s), s.id]}, {include_blank: true}, class: 'form-select'
  .row.mb-3
    = f.label :notes, 'Notes', class: 'col-sm-3'
    .col-sm-9
      = f.text_area :notes, rows: 3, class: 'form-control'
  .row.mb-3
    .col.offset-sm-3
      = submit_tag button_title, class: 'btn btn-primary'

app/views/runs/_form_error.html.haml
- if run.errors.any?
  .alert.alert-danger
    %p #{pluralize(run.errors.count, 'error')} prohibited this run from being saved:
    %ul
      - run.errors.full_messages.each do |msg|
        %li=msg

app/views/runs/_intensity_calc.html.haml
.modal#intensity-calc
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title Calculate intensity
        %button.btn-close{type: 'button', 'data-bs-dismiss': 'modal', 'aria-label': 'Close'}
      .modal-body
        = form_tag do
          .row.mb-3.align-items-center
            = label_tag :easy, 'Easy', class: 'col-sm-3 col-form-label'
            .col-sm-3
              = text_field_tag :easy, nil, data: {weight: 0.2, target: 'easy_total'}, class: 'form-control intensity-input'
            %label.col-sm-3
              &times; 0.2 =
            .col-sm-3
              = text_field_tag :easy_total, 0.0, class: 'form-control intensity-subtotal', disabled: true
          .row.mb-3.align-items-center
            = label_tag :marathon, 'Marathon', class: 'col-sm-3 col-form-label'
            .col-sm-3
              = text_field_tag :marathon, nil, data: {weight: 0.4, target: 'marathon_total'}, class: 'form-control intensity-input'
            %label.col-sm-3
              &times; 0.4 =
            .col-sm-3
              = text_field_tag :marathon_total, 0.0, class: 'form-control intensity-subtotal', disabled: true
          .row.mb-3.align-items-center
            = label_tag :threshold, 'Threshold', class: 'col-sm-3 col-form-label'
            .col-sm-3
              = text_field_tag :threshold, nil, data: {weight: 0.6, target: 'threshold_total'}, class: 'form-control intensity-input'
            %label.col-sm-3
              &times; 0.6 =
            .col-sm-3
              = text_field_tag :threshold_total, 0.0, class: 'form-control intensity-subtotal', disabled: true
          .row.mb-3.align-items-center
            = label_tag :ten_k, '10k effort', class: 'col-sm-3 col-form-label'
            .col-sm-3
              = text_field_tag :ten_k, nil, data: {weight: 0.8, target: 'ten_k_total'}, class: 'form-control intensity-input'
            %label.col-sm-3
              &times; 0.8 =
            .col-sm-3
              = text_field_tag :ten_k_total, 0.0, class: 'form-control intensity-subtotal', disabled: true
          .row.mb-3.align-items-center
            = label_tag :interval, 'Interval', class: 'col-sm-3 col-form-label'
            .col-sm-3
              = text_field_tag :interval, nil, data: {weight: 1.0, target: 'interval_total'}, class: 'form-control intensity-input'
            %label.col-sm-3
              &times; 1.0 =
            .col-sm-3
              = text_field_tag :interval_total, 0.0, class: 'form-control intensity-subtotal', disabled: true
          .row.mb-3.align-items-center
            = label_tag :repetition, 'Repetition', class: 'col-sm-3 col-form-label'
            .col-sm-3
              = text_field_tag :repetition, nil, data: {weight: 1.5, target: 'repetition_total'}, class: 'form-control intensity-input'
            %label.col-sm-3
              &times; 1.5 =
            .col-sm-3
              = text_field_tag :repetition_total, 0.0, class: 'form-control intensity-subtotal', disabled: true
          .row.mb-3.align-items-center
            %label.col-sm-9
              Total
            .col-sm-3
              = text_field_tag :grand_total, 0.0, class: 'form-control', disabled: true
      .modal-footer
        %button.btn.btn-secondary{'data-bs-dismiss': 'modal'} Cancel
        %button.btn.btn-primary#intensity-confirm{'data-bs-dismiss': 'modal'} Use

app/views/runs/_run.html.haml
- row_class = run.is_night? ? 'night' : nil
- row_class = 'table-warning' if run.is_race?
- rain = run.precip?

%tr{class: row_class, title: (run.race_name if run.is_race?)}
  %td.start_time
    = link_to local_date_time_string(run.start_time), run
  %td
    #{'%.2f' % run.distance} mi
    - if run.is_race?
      %i.fas.fa-flag-checkered{title: '(race)'}
  %td
    #{run.duration_string}
    %small
      (#{run.pace_string})
  %td.weather{class: "#{temp_class(run.temperature)} #{'rain' if rain}", title: ('rain' if rain)}
    - if run.weather_type
      = build_weather_icon(run)
    - unless run.temperature.nil?
      #{run.temperature}&deg;F
  %td
    - unless run.elev_gain.nil?
      #{run.elev_gain} ft
      %small
        (#{'%.1f' % run.climb_rate} ft/mi)
  - if run.notes?
    %td{title: run.notes, 'data-toggle': 'tooltip'}
      = build_icon('comment-alt')
  - else
    %td

app/views/runs/_similar_run.html.haml
%tr.text-center
  %td=link_to local_date_time_string(run.start_time), run
  %td #{'%.2f' % run.distance} mi
  %td{class: temp_class(run.temperature)}
    - if run.weather_type
      = build_weather_icon(run)
    - unless run.temperature.nil?
      #{run.temperature}&deg;F
  %td #{run.elev_gain} ft
  %td #{'%.3f' % similarity}

app/views/runs/edit.html.haml
- provide(:title, 'Edit run')
%h1 Editing run
= render 'form', button_title: 'Update', run: @run
= link_to 'Show', @run, class: 'btn btn-info'
= link_to 'Back', runs_path, class: 'btn btn-warning'

app/views/runs/index.html.haml
- page_title = build_page_title(params)
- provide(:title, page_title)

.row
  .col-12
    %h1=page_title
    .text-center
      = will_paginate(@runs, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer)
    .card
      .card-header
        = page_entries_info
        = link_to build_icon('search'), search_runs_path, style: 'float: right'
      %table.table.table-sm.table-hover.runs
        %thead
          %tr
            %th Start time
            %th Distance
            %th Duration
            %th Weather
            %th Climb
            %th Notes
        = render @runs
    .text-center
      = will_paginate(@runs, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer)
    = link_to 'New Run', new_run_path, class: 'btn btn-large btn-success'

app/views/runs/new.html.haml
- provide(:title, 'New run')
%h1 New run
= render 'form', button_title: 'Create', run: @run
= link_to 'Back', runs_path, class: 'btn btn-warning'

app/views/runs/search.html.haml
- provide(:title, 'Search runs')

%h1
  Search runs
= form_tag({controller: 'runs', action: 'index'}, method: 'get') do
  .row.mb-3.align-items-center
    .col-sm-2
      .form-check
        = check_box_tag :filter_date, true, false, class: 'form-check-input'
        %label.form-check-label
          = label_tag :filter_date, 'Date'
    = label_tag :start_date, 'from', class: 'col-sm-2 col-form-label'
    .col-sm-3
      .input-group#start-date{'data-target-input': 'nearest'}
        = text_field_tag :start_date, @start_date, class: 'form-control datetimepicker-input', id: 'start-date', 'data-target': '#start-date'
        .input-group-text{data: {target: '#start-date', toggle: 'datetimepicker'}}
          %i.fas.fa-calendar
    = label_tag :end_date, 'to', class: 'col-sm-2 col-form-label'
    .col-sm-3
      .input-group#end-date{'data-target-input': 'nearest'}
        = text_field_tag :end_date, @end_date, class: 'form-control datetimepicker-input', id: 'end-date', 'data-target': '#end-date'
        .input-group-text{data: {target: '#end-date', toggle: 'datetimepicker'}}
          %i.fas.fa-calendar
  .row.mb-3.align-items-center
    .col-sm-2
      .form-check
        = check_box_tag :filter_dist, true, false, class: 'form-check-input'
        %label.form-check-label
          = label_tag :filter_dist, 'Distance'
    = label_tag :min_dist, 'min', class: 'col-sm-2 col-form-label'
    .col-sm-3
      .input-group
        = number_field_tag :min_dist, 0, class: 'form-control', step: 0.01, min: 0
        .input-group-text miles
    = label_tag :max_dist, 'max', class: 'col-sm-2 col-form-label'
    .col-sm-3
      .input-group
        = number_field_tag :max_dist, 100, class: 'form-control', step: 0.01, min: 0
        .input-group-text miles
  .row.mb-3.align-items-center
    .col-sm-2
      .form-check
        = check_box_tag :filter_temp, true, false, class: 'form-check-input'
        %label.form-check-label
          = label_tag :filter_temp, 'Temperature'
    = label_tag :min_temp, 'min', class: 'col-sm-2 col-form-label'
    .col-sm-3
      .input-group
        = number_field_tag :min_temp, 0, class: 'form-control', step: 1, min: -20, max: 120
        .input-group-text &deg;F
    = label_tag :max_temp, 'max', class: 'col-sm-2 col-form-label'
    .col-sm-3
      .input-group
        = number_field_tag :max_temp, 100, class: 'form-control', step: 1, min: -20, max: 120
        .input-group-text &deg;F
  .row.mb-3
    .col-sm-6
      = submit_tag 'Search', class: 'btn btn-primary'

app/views/runs/show.html.haml
- if @run.is_race?
  - page_title = @run.race_name || "Race on #{@run.start_time.strftime('%B %e, %Y')}"
  - page_header = @run.race_name || "#{@run.time_of_day} race"
- else
  - page_title = @run.start_time.strftime('%B %e, %Y')
  - page_header = "#{@run.time_of_day} run"
- provide(:title, page_title)

.row
  .run-date-header.col-3.col-sm-2
    .card
      .card-header.bg-primary.text-center.text-white
        = @run.start_time.strftime('%b')
      .card-body.text-center
        = @run.start_time.day
  .col-6.col-sm-7
    %h1.text-left=page_header
    %h5.text-left=local_time_string(@run.start_time)
.row.row-cols-1.row-cols-sm-2.row-cols-md-3
  .col
    .card{class: ('bg-success text-white' if @run.distance_record?)}
      .card-header.bg-primary.text-white Total distance
      .card-body
        %h4.card-title
          = build_icon('road')
          #{'%.2f' % @run.distance} miles
  - if @run.duration?
    .col
      .card
        .card-header.bg-primary.text-white Total duration
        .card-body
          %h4.card-title
            = build_icon('hourglass-end')
            = @run.duration_string
    .col
      .card{class: ('bg-success text-white' if @run.pace_record?)}
        .card-header.bg-primary.text-white Average pace
        .card-body
          %h4.card-title
            = build_icon('stopwatch')
            = @run.pace_string
  - unless @run.temperature.nil?
    .col
      .card
        .card-header.bg-primary.text-white Weather
        .card-body{class: ('precip' if @run.precip?)}
          %h4.card-title
            %span{class: temp_class(@run.temperature)}
              - if @run.weather_type
                = build_weather_icon(@run)
              #{@run.temperature}&deg;F
          - unless @run.humidity.nil?
            %p.card-text #{@run.humidity}% humidity
  - unless @run.elev_gain.nil?
    .col
      .card
        .card-header.bg-primary.text-white Total elevation gain
        .card-body
          %h4.card-title
            = build_icon('external-link-square-alt')
            #{@run.elev_gain} feet
  - if @run.heart_rate
    .col
      .card
        .card-header.bg-primary.text-white Average heart rate
        .card-body
          %h4.card-title
            = build_icon('heartbeat')
            #{@run.heart_rate} bpm
          - unless @run.intensity.nil?
            %p.card-text #{@run.intensity} intensity points
  - if @run.shoe
    .col
      .card.shoe-card{style: "background: ##{@run.shoe.dark_color.hex}; color: ##{@run.shoe.bright_color.hex}"}
        .card-header.bg-primary.text-white Shoes
        .card-body
          %h4.card-title
            = build_icon('shoe-prints')
            = link_to @run.shoe_name,
                      shoe_path(@run.shoe)
          %p.card-text #{@run.shoe_mileage} miles
- if @run.notes?
  .card
    .card-header.bg-secondary.text-white Notes
    .card-body=@run.notes
- if @run.can_be_compared?
  .card
    .card-header.bg-secondary.text-white Similar runs
    %table.table
      %tr
        %th Date
        %th Distance
        %th Weather
        %th Climb
        %th Similarity score
      - @run.similar_runs.each do |r|
        = render 'similar_run', run: r[:run], similarity: r[:similarity]
.btn-toolbar{role: 'toolbar'}
  .btn-group.me-2{role: 'group'}
    = link_to 'All Runs', runs_path, class: 'btn btn-info'
  .btn-group.me-2{role: 'group'}
    = link_to 'Previous', run_path(@run.previous), class: 'btn btn-secondary' if @run.previous
    = link_to 'Next', run_path(@run.next), class: 'btn btn-secondary' if @run.next
  .btn-group.me-2{role: 'group'}
    = link_to 'New Run', new_run_path, class: 'btn btn-success'
  .btn-group.me-2{role: 'group'}
    = link_to 'Edit', edit_run_path(@run), class: 'btn btn-warning'
    = link_to 'Delete', @run, data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'