config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  resources :runs do
    collection do
      get 'search'
    end
  end
  resources :shoes
  resources :weather_types, except: [:show]
  get 'training' => 'static_pages#training'
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  has_many :runs

  scope :active, -> { where retired: false }

  validates :manufacturer, presence: true
  validates :model, presence: true
  validates :color_primary, presence: true
  validates :color_secondary, presence: true
  validates :size, numericality: true

  BRIGHTNESS_THRESHOLD = 0.2

  def mileage(as_of: Time.now)
    runs.where('start_time <= ?', as_of).inject(0) { |a, b| a + b.distance }
  end

  def last_run
    runs.max_by(&:start_time)
  end

  def last_used
    last_run.start_time rescue nil
  end

  def last_used_local_string
    last_used ? last_used.strftime('%a %-m/%-d/%y') : 'never'
  end

  def bright_color
    max = colors.max { |a, b| a.brightness <=> b.brightness }
    min = colors.min { |a, b| a.brightness <=> b.brightness }
    if max.brightness > min.brightness + BRIGHTNESS_THRESHOLD
      max
    else
      tert = Color::RGB.by_hex(color_tertiary)
      tert.brightness > max.brightness ? tert : max
    end
  end

  def dark_color
    max = colors.max { |a, b| a.brightness <=> b.brightness }
    min = colors.min { |a, b| a.brightness <=> b.brightness }
    if min.brightness < max.brightness - BRIGHTNESS_THRESHOLD
      min
    else
      tert = Color::RGB.by_hex(color_tertiary)
      tert.brightness < min.brightness ? tert : min
    end
  end

  private

  def colors
    [color_primary, color_secondary].collect { |c| Color::RGB.by_hex(c) }
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def index
    @shoes = Shoe.all.sort_by do |s|
      s.last_used.nil? ? Time.now : s.last_used
    end.reverse.paginate(per_page: 20, page: params[:page])
  end

  def show
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render xml: @shoe }
    end
  end

  def new
    @shoe = Shoe.new
  end

  def edit
    @shoe = Shoe.find(params[:id])
  end

  def create
    @shoe = Shoe.new(shoe_params)
    if @shoe.save
      flash[:success] = 'Shoe was successfully created.'
      redirect_to @shoe
    else
      flash[:danger] = @shoe.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    @shoe = Shoe.find(params[:id])
    if @shoe.update(shoe_params)
      flash[:success] = 'Shoe was successfully updated.'
      redirect_to @shoe
    else
      flash[:danger] = @shoe.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @shoe = Shoe.find(params[:id])
    @shoe.destroy
    flash[:success] = 'Shoe was successfully deleted.'
    redirect_to shoes_url
  end

  private

  def shoe_params
    params.require(:shoe).permit(:manufacturer, :model, :color_primary,
                                 :color_secondary, :color_tertiary, :size,
                                 :retired)
  end
end

app/helpers/shoes_helper.rb
# frozen_string_literal: true

module ShoesHelper
  def shoe_size_clean(size)
    half = '&frac12;'
    "#{size.floor}#{half if Rational(size).denominator == 2}".html_safe
  end

  def colors_for_display(shoe_color)
    style = "background: ##{shoe_color}"
    style += '; color: black' if Color::RGB.by_hex(shoe_color).brightness > 0.75
    style
  end

  def model_with_mileage(shoe)
    "#{shoe.model} (#{shoe.mileage.round(2)} mi)"
  end
end

app/views/shoes/_form.html.haml
= form_for(shoe) do |f|
  .row.mb-3
    = f.label :manufacturer, 'Manufacturer', class: 'col-sm-3 col-form-label'
    .col-sm-3
      = f.text_field :manufacturer, class: 'form-control'
  .row.mb-3
    = f.label :model, 'Model', class: 'col-sm-3 col-form-label'
    .col-sm-3
      = f.text_field :model, class: 'form-control'
  .row.mb-3
    = f.label :size, 'Size', class: 'col-sm-3 col-form-label'
    .col-sm-3
      = f.number_field :size, step: 0.5, in: 1..20, class: 'form-control'
  .row.mb-3
    = f.label :color_primary, 'Color 1', class: 'col-sm-3 col-form-label'
    .col-sm-3
      .input-group
        .input-group-text #
        = f.text_field :color_primary, maxlength: 6, class: 'form-control'
  .row.mb-3
    = f.label :color_secondary, 'Color 2', class: 'col-sm-3 col-form-label'
    .col-sm-3
      .input-group
        .input-group-text #
        = f.text_field :color_secondary, maxlength: 6, class: 'form-control'
  .row.mb-3
    = f.label :color_tertiary, 'Color 3', class: 'col-sm-3 col-form-label'
    .col-sm-3
      .input-group
        .input-group-text #
        = f.text_field :color_tertiary, maxlength: 6, class: 'form-control'
  .row.mb-3
    .col-sm-4.col-md-3.offset-sm-3
      .form-check
        = f.check_box :retired, class: 'form-check-input'
        %label.form-check-label
          Retired
  .row.mb-3
    .col-sm-6.offset-sm-3
      = submit_tag button_title, class: 'btn btn-primary'

app/views/shoes/_shoe.html.haml
%tr
  %td=shoe.manufacturer
  %td=link_to shoe.model, shoe_path(shoe)
  %td
    %span.badge{style: colors_for_display(shoe.color_primary)} 1
    %span.badge{style: colors_for_display(shoe.color_secondary)} 2
    %span.badge{style: colors_for_display(shoe.color_tertiary)} 3
  %td=shoe_size_clean(shoe.size)
  %td
    = shoe.last_used_local_string
    - if shoe.retired?
      %span.badge.rounded-pill.bg-secondary{title: 'retired'} r
  %td=shoe.runs.count
  %td=shoe.mileage.round(2)

app/views/shoes/edit.html.haml
- provide(:title, 'Edit shoe')
%h1 Editing shoe
= render 'form', button_title: 'Update', shoe: @shoe
= link_to 'Show', @shoe, class: 'btn btn-info'
= link_to 'Back', shoes_path, class: 'btn btn-warning'

app/views/shoes/index.html.haml
- provide(:title, 'Shoes')
.row
  .col-12
    %h1 Shoes
    .text-center
      = will_paginate(@runs, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer)
    .card
      .card-header=page_entries_info
      %table.shoes.table.table-hover
        %thead
          %tr
            %th Manufacturer
            %th Model
            %th Colors
            %th Size
            %th Last used
            %th Runs
            %th Mileage
        = render @shoes
    .text-center
      = will_paginate(@runs, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer)
    = link_to 'New Shoe', new_shoe_path, class: 'btn btn-success'

app/views/shoes/new.html.haml
- provide(:title, 'New shoe')
%h1 New shoe
= render 'form', button_title: 'Create', shoe: @shoe
= link_to 'Back', shoes_path, class: 'btn btn-warning'

app/views/shoes/show.html.haml
- provide(:title, 'View shoe')
%h1
  #{@shoe.manufacturer}
  #{@shoe.model}
  - if @shoe.retired?
    %span.badge.rounded-pill.bg-secondary retired
.row.row-cols-1.row-cols-sm-2.row-cols-md-3
  .col
    .card
      .card-header.bg-primary.text-white Size
      .card-body
        %h4.card-title=shoe_size_clean(@shoe.size)
  .col
    .card
      .card-header.bg-primary.text-white Colors
      .card-body
        %p.card-text
          %span.badge{style: colors_for_display(@shoe.color_primary)}
            color 1
          %span.badge{style: colors_for_display(@shoe.color_secondary)}
            color 2
          %span.badge{style: colors_for_display(@shoe.color_tertiary)}
            color 3
  .col
    .card
      .card-header.bg-primary.text-white Mileage
      .card-body
        %h4.card-title=@shoe.mileage.round(2)
.btn-toolbar{role: 'toolbar'}
  .btn-group.me-2{role: 'group'}
    = link_to 'All Shoes', shoes_path, class: 'btn btn-info'
  .btn-group.me-2{role: 'group'}
    = link_to 'New Shoe', new_shoe_path, class: 'btn btn-success'
  .btn-group.me-2{role: 'group'}
    = link_to 'Edit', edit_shoe_path(@shoe), class: 'btn btn-warning'
    = link_to 'Delete', @shoe, data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger'