config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  resources :runs do
    collection do
      get 'search'
    end
  end
  resources :shoes
  resources :weather_types, except: [:show]
  get 'training' => 'static_pages#training'
end

app/views/layouts/_alert.html.haml
%div{aria: {live: 'polite', atomic: 'true'}, style: 'position: relative'}
  %div{style: 'position: absolute; top: 0; right: 0'}
    - %i(success info warning danger).each do |type|
      - if flash[type]
        .toast{role: 'alert', aria: {live: 'assertive', atomic: 'true'}, 'data-delay': 1000}
          .toast-header{class: "bg-#{type}"}
            %strong Alert
          .toast-body
            = flash[type]
:coffee
  $('.toast').toast('show')

app/views/layouts/_footer.html.haml
%footer.footer.col-12
  %small
    Run Log
  %nav
    %ul
      -# to be filled in later
      -# syntax: %li=link_to 'About', '#'

app/views/layouts/_header.html.haml
%nav.navbar.fixed-top.navbar-expand-lg.navbar-dark.bg-primary{role: 'navigation'}
  .container
    = link_to 'Run Log', root_path, id: 'logo', class: 'navbar-brand'
    %button.navbar-toggler{type: 'button',
                           data: {toggle: 'collapse', target: '#navbar1'},
                           aria: {controls: 'navbar1', expanded: 'false', label: 'Toggle nav'}}
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar1
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to 'Runs', runs_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Shoes', shoes_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Weather', weather_types_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Training', training_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title=full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{rel: 'stylesheet', href: 'http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css'}
    %script{src: 'http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js'}
    %script{src: "https://kit.fontawesome.com/978a46eab9.js", crossorigin: "anonymous"}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/alert'
      = yield
      = render 'layouts/footer'